(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['exp_pro.html'] = template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [2,'>= 1.0.0-rc.3'];
helpers = helpers || Handlebars.helpers; data = data || {};
  


  return "<!DOCTYPE html>\r\n<html>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/css/bootstrap.css\">\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\r\n	<head>\r\n	\r\n	</head>\r\n	<body>		\r\n	    <table class =\"table table-bordered\">\r\n			<tr>\r\n				<th> Quand ? </th>\r\n				<th> Quoi ? </th>\r\n				<th> D&eacute;tails </th> \r\n			</tr>\r\n			<tr>\r\n				<td> Depuis d&eacute;cembre 2010 </td>\r\n				<td> Ing&eacute;nieur jeune dipl&ocirc;m&eacute;e dans l&acute;&eacute;quipe MIMETIC de l&acute;Inria Rennes.\r\nConception d&acute;une plateforme logicielle permettant la simulation de foules gr&acirc;ce &agrave; des m&eacute;thodes de\r\npeuplement massif.\r\n </td>\r\n 				<td> <img src=\"foule.png\"> </td>\r\n			</tr>\r\n			<tr>\r\n				<td> Mars - Septembre 2010 </td>\r\n				<td> Stage dans le d&eacute;partement R&D de Mac Guff Ligne, studio d&acute;effets\r\nsp&eacute;ciaux et animation. D&eacute;veloppement de structures permettant l&acute;am&eacute;lioration et l&acute;acc&eacute;l&eacute;ration du\r\nrendu des images. (C/C++)\r\n				 </td>\r\n				<td> <img src = \"http://www.actucine.com/wp-content/uploads/2012/06/Le-Lorax.jpg\" > </td>\r\n			</tr>\r\n			<tr>\r\n				<td> Juin - Septembre 2009 </td>\r\n				<td> Stage dans le d&eacute;partement R&D du site Flowserve d&acute;Arnage (pr&egrave;s du Mans). \r\n					 Conception d&acute;une application permettant d&acute;automatiser le trac&eacute; de corps de pompe hydraulique (C#) \r\n				 </td>\r\n				<td> <img src = \"http://1.bp.blogspot.com/-2z2LfE77XDQ/Ty_6VU7LlII/AAAAAAAAAkc/wUe90o6ExaQ/s1600/Flowserve-Logo-web.jpg\" > </td>\r\n			</tr>\r\n		</table>	\r\n	</body>\r\n</html>";
  });
})();